version: '3'
services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:0-20-bullseye
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file: ./.env
    environment:
      NODE_ENV: development
      FONTAWESOME_KEY: ${FONTAWESOME_KEY}
    depends_on:
      - mongo
    networks:
      - node-gitdb

  db:
    build:
      context: .
      dockerfile: ./Mongo.Dockerfile
    env_file: ./.env
    container_name: db # Ensures the container name is 'db'
    hostname: db # Sets the internal hostname to 'db'
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "bash", "/usr/local/bin/mongodb_healthcheck.sh" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_REPLICA_SET_NAME=${MONGO_REPLICA_SET_NAME}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_KEYFILE=${MONGO_KEYFILE}
      - MONGO_DB_PATH=${MONGO_DB_PATH}
      - DB_HOST=127.0.0.1:27017
    network_mode: host

volumes:
  mongodb-data:


networks:
  node-gitdb:
